# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

test: &test
  steps:
    - checkout
    - run: |
        pip install -r dev-requirements.txt
        pip install .
        pytest tests --junit-xml test_output/junit.xml
    - store_test_results:
        path: test_output

jobs:
  py37:
    <<: *test
    docker:
      - image: circleci/python:3.7

  py38:
    <<: *test
    docker:
      - image: circleci/python:3.8

  py39:
    <<: *test
    docker:
      - image: circleci/python:3.9

  lint:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: |
          pip install black
          black --check --line-length 80 kf_lib_data_ingest tests
      - run: |
          pip install flake8
          flake8 --ignore=E501,W503,E203 kf_lib_data_ingest
          flake8 --ignore=E501,W503,E203 tests

  docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: |
          pip install -r doc-requirements.txt
          doc8 docs/source
          make -C docs html
      - add_ssh_keys:
          fingerprints:
              - "64:fd:f9:62:bb:b3:48:56:a4:bb:17:9f:f8:e5:b8:7f"
      - deploy:
          name: deploy docs to github pages
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
                ./scripts/deploy-ghpages.sh
            fi


workflows:
  version: 2
  build:
    jobs:
      - py37
      - py38
      - py39
      - lint
      - docs
